[package]
name = "ghostemp"
version = "0.1.2"
edition = "2021"
description = "Http Server Simple"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "*"
serde_json = "*"
openssl = { version = "0.10.44" }
